model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "./sd-models/sd_xl_base_1.0.safetensors"
train_data_dir = "/data/lora-scripts/train/th"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
output_name = "lora-character-cute"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = 20
train_batch_size = 1
gradient_checkpointing = false
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.00001
unet_lr = 0.00001
text_encoder_lr = 0.000001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora"
network_dim = 64
network_alpha = 32
sample_prompts = "lora:chibi-style:1, transform into cute，chibi-style character style, 1girl --n lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry,  --w 1024  --h 1024  --l 7  --s 24  --d 1337"
sample_sampler = "euler_a"
sample_every_n_epochs = 2
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
max_token_length = 255
seed = 1337
mixed_precision = "fp16"
full_bf16 = false
no_half_vae = true
xformers = true
sdpa = false
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
